# Generated by Django 2.1.7 on 2019-03-31 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0002_entry'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='duration',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
